# Generated by Django 3.0.6 on 2020-05-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190409_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='added',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author_email',
        ),
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='book',
            name='imported',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='price',
        ),
        migrations.RemoveField(
            model_name='book',
            name='published',
        ),
        migrations.RemoveField(
            model_name='book',
            name='published_time',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(blank=True, max_length=150, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='book',
            name='id_people',
            field=models.CharField(blank=True, max_length=150, verbose_name='id_people'),
        ),
        migrations.AddField(
            model_name='book',
            name='latitude_home',
            field=models.CharField(blank=True, max_length=150, verbose_name='latitude_home'),
        ),
        migrations.AddField(
            model_name='book',
            name='latitude_other',
            field=models.CharField(blank=True, max_length=150, verbose_name='latitude_other'),
        ),
        migrations.AddField(
            model_name='book',
            name='longitude_home',
            field=models.CharField(blank=True, max_length=150, verbose_name='longitude_home'),
        ),
        migrations.AddField(
            model_name='book',
            name='longitude_other',
            field=models.CharField(blank=True, max_length=150, verbose_name='longitude_other'),
        ),
    ]
