# Generated by Django 3.0.6 on 2020-05-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200524_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='work_or_other',
            field=models.CharField(blank=True, max_length=150, verbose_name='work_or_other'),
        ),
    ]
