# Generated by Django 3.0.6 on 2020-05-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_book_work_or_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='latitude_home',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, verbose_name='latitude_home'),
        ),
        migrations.AlterField(
            model_name='book',
            name='latitude_other',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, verbose_name='latitude_other'),
        ),
        migrations.AlterField(
            model_name='book',
            name='longitude_home',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, verbose_name='longitude_home'),
        ),
        migrations.AlterField(
            model_name='book',
            name='longitude_other',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=19, verbose_name='longitude_other'),
        ),
    ]
